### ISSUE TITLE
Write resolved hosts to a file

### ISSUE THREAD

**Issue by ghost** [mersinvald/batch_resolve#14]
**Describe the solution you'd like**
Great tool, tried it once and fell in ❤❤. However it would be great to write the resolved hosts/domains to a separate file or append to the output. eg 

```172.217.0.238,music.google.com```
```172.217.164.238,google.com```
```31.13.65.36,facebook.com```

**Comment by mersinvald** [comment]
Nice idea, would csv file be okay for you?

**Comment by mersinvald** [comment]
@ghost Just merged the PR: https://github.com/mersinvald/batch_resolve/pull/15, gonna do a release in AUR shortly,

**Comment by mersinvald** [comment]
Oh, I've been making a feature for a deleted user. Great!

**Comment by copy-and-paste** [comment]
Hey, just landed on this dope tool, however that csv option would be nice. I see its not implemented

**Comment by mersinvald** [comment]
@copy-and-paste sorry for slow reaction time.

Yeah, looking back, the implementation I've merged in is "space-separated values", not csv.
Anyway, you can use .cvs extension on your output files to get the space-separated source->dest pairs

Should be straightforward to parse
